'use client';
import {createContext,useContext,useState,useEffect,useCallback} from 'react';
import {projects as seedProjects,documents as seedDocuments,analyses as seedAnalyses} from '@/services/mock-data';
import type {Project,DocumentRecord,Analysis,Quant,Budget,ProjectAsset,AgentExecution,AgentFeedback,ProjectPending,KanbanCard,RadarAccess,ProjectTemplate} from '@/types';
const seedPendings:ProjectPending[]=[{id:'pending-1',projectId:'1',title:'RRT atualizado não localizado',type:'Documento faltante',detail:'O ArqCheck identificou que o RRT atualizado ainda não está na base do projeto.',assignee:'Lucas Costa',priority:'Alta',dueDate:'2026-09-22',status:'Aguardando cliente',source:'IA',documentIds:['4']},{id:'pending-2',projectId:'1',title:'Revisar divergência de área',type:'Revisão humana',detail:'Confirmar qual área deve prevalecer entre memorial e planta executiva.',assignee:'Ana Martins',priority:'Crítica',dueDate:'2026-09-20',status:'Aberta',source:'IA',documentIds:['1','2']},{id:'pending-3',projectId:'1',title:'Aprovar cenário base do orçamento',type:'Orçamento',detail:'O orçamento foi gerado e aguarda validação antes de ser enviado ao cliente.',assignee:'Beatriz Melo',priority:'Média',dueDate:'2026-09-25',status:'Em andamento',source:'Equipe'}];
const seedKanban:KanbanCard[]=[{id:'kanban-1',projectId:'1',title:'RRT atualizado não localizado',column:'Aguardando documento',type:'Pendência da IA',assignee:'Lucas Costa',priority:'Alta',dueDate:'2026-09-22',detail:'Solicitar documento ao cliente.',pendingId:'pending-1',documentIds:['4']},{id:'kanban-2',projectId:'1',title:'Revisar divergência de área',column:'Em revisão humana',type:'ArqCheck',assignee:'Ana Martins',priority:'Crítica',dueDate:'2026-09-20',detail:'Memorial e planta apresentam áreas diferentes.',pendingId:'pending-2',documentIds:['1','2']},{id:'kanban-3',projectId:'1',title:'Aprovar cenário base do orçamento',column:'Aguardando resposta',type:'ArqBudget',assignee:'Beatriz Melo',priority:'Média',dueDate:'2026-09-25',detail:'Validar valores antes do envio.',pendingId:'pending-3'}];
const seedRadarAccess:RadarAccess={general:true,regional:true,project:true,financial:true,operational:true,productivity:true,sensitive:false,region:'Matriz Recife'};
const seedTemplates:ProjectTemplate[]=[{id:'template-1',projectId:'1',name:'Parecer Studio · Verde editorial',kind:'Projeto',format:'Parecer',status:'Ativo',updatedAt:'2026-09-10',default:true},{id:'template-2',projectId:'1',name:'Relatório técnico corporativo',kind:'Empresa',format:'Relatório',status:'Ativo',updatedAt:'2026-09-04'},{id:'template-3',projectId:'2',name:'Proposta Casa JCP',kind:'Cliente',format:'Proposta',status:'Rascunho',updatedAt:'2026-09-01'}];
type DemoState={projects:Project[];documents:DocumentRecord[];analyses:Analysis[];quants:Quant[];budgets:Budget[];assets:ProjectAsset[];agentRuns:AgentExecution[];agentFeedback:AgentFeedback[];pendings:ProjectPending[];kanban:KanbanCard[];radarAccess:RadarAccess;templates:ProjectTemplate[]};
type DemoContext=DemoState&{update:(fn:(s:DemoState)=>DemoState)=>void;notice:(s:string)=>void;ready:boolean};
const Context=createContext<DemoContext|null>(null);
export function DemoProvider({children}:{children:React.ReactNode}){const[state,setState]=useState<DemoState>({projects:seedProjects,documents:seedDocuments,analyses:seedAnalyses,quants:[{id:'quant-1',projectId:'2',date:'2026-09-07',area:148.7}],budgets:[],assets:[],agentRuns:[],agentFeedback:[],pendings:seedPendings,kanban:seedKanban,radarAccess:seedRadarAccess,templates:seedTemplates});const[message,setMessage]=useState('');const[ready,setReady]=useState(false);useEffect(()=>{try{const saved=sessionStorage.getItem('arq-demo-v1');if(saved){const parsed=JSON.parse(saved);setState({...parsed,budgets:parsed.budgets||[],assets:parsed.assets||[],agentRuns:parsed.agentRuns||[],agentFeedback:parsed.agentFeedback||[],pendings:parsed.pendings||seedPendings,kanban:parsed.kanban||seedKanban,radarAccess:parsed.radarAccess||seedRadarAccess,templates:parsed.templates||seedTemplates})}}catch{}setReady(true)},[]);useEffect(()=>{if(ready)sessionStorage.setItem('arq-demo-v1',JSON.stringify(state))},[state,ready]);useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(''),4300);return()=>clearTimeout(t)}},[message]);const notice=useCallback((s:string)=>setMessage(s),[]);return <Context.Provider value={{...state,update:setState,notice,ready}}>{children}{message&&<div className="toast" role="status"><span>✓</span>{message}<button onClick={()=>setMessage('')} aria-label="Fechar aviso">×</button></div>}</Context.Provider>}
export function useDemo(){const c=useContext(Context);if(!c)throw Error('DemoProvider ausente');return c}
