'use client';
import {useState,Suspense} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {ScanLine,LoaderCircle,ArrowUpRight,TriangleAlert} from 'lucide-react';
import {PageHeader,Picker,StatusBadge,ChartCard} from '@/components/common';
import {useDemo} from '@/hooks/use-demo';
import {date,initialIssues} from '@/services/mock-data';
function riskFromScore(score:number){return score>=90?'Baixo':score>=75?'Médio':'Alto'}
function ArqCheckView(){const{projects,documents,analyses,update,notice}=useDemo();const params=useSearchParams();const router=useRouter();const[project,setProject]=useState(projects.find(p=>p.id===params.get('project'))?.name||projects[0].name);const[running,setRunning]=useState(false);const openIssues=analyses.reduce((s,a)=>s+a.issues.filter(i=>!i.resolved).length,0);async function run(){setRunning(true);await new Promise(r=>setTimeout(r,1400));const p=projects.find(pr=>pr.name===project)!;const docs=documents.filter(d=>d.projectId===p.id).length;const issues=initialIssues();const analysis={id:`check-${Date.now()}`,projectId:p.id,date:'2026-09-07',score:100-issues.length*3,documents:docs||8,issues};update(s=>({...s,analyses:[analysis,...s.analyses]}));setRunning(false);notice('Análise concluída pela IA.');router.push(`/arqcheck/${analysis.id}`)}return <><PageHeader eyebrow="ARQCHECK AI" title="ArqCheck AI" description="Analise documentos automaticamente e antecipe inconsistências antes da entrega."><Picker label="Projeto" value={project} onChange={setProject} options={projects.map(p=>p.name)}/><button className="btn primary" onClick={run} disabled={running}>{running?<><LoaderCircle className="spin" size={16}/>Analisando documentos...</>:<><ScanLine size={16}/>Nova análise</>}</button></PageHeader><div className="metrics four"><MetricCardLike label="Análises realizadas" value={analyses.length}/><MetricCardLike label="Pendências abertas" value={openIssues}/><MetricCardLike label="Pendências resolvidas" value={analyses.flatMap(a=>a.issues).filter(i=>i.resolved).length}/><MetricCardLike label="Score médio" value={`${Math.round(analyses.reduce((s,a)=>s+a.score,0)/analyses.length)}%`}/></div><ChartCard title="Análises realizadas" subtitle="Cada análise identifica divergências entre os documentos enviados">{analyses.map(a=>{const p=projects.find(pr=>pr.id===a.projectId);const open=a.issues.filter(i=>!i.resolved).length;return <Link key={a.id} href={`/arqcheck/${a.id}`} className="focus-project"><span className="project-symbol"><ScanLine size={19}/></span><div><strong>{p?.name||'Projeto removido'}</strong><small>{date(a.date)} · {a.documents} documentos analisados</small></div>{open>0&&<span className="badge amber"><TriangleAlert size={12}/>{open} pendências</span>}<StatusBadge value={riskFromScore(a.score)}/><ArrowUpRight size={16}/></Link>})}</ChartCard></>}
function MetricCardLike({label,value}:{label:string;value:string|number}){return <div className="metric"><div className="metric-label">{label}</div><strong>{value}</strong></div>}
export default function Page(){return <Suspense><ArqCheckView/></Suspense>}
