'use client';
import {useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,Check,MessageSquare,Download} from 'lucide-react';
import {PageHeader,StatusBadge} from '@/components/common';
import {useDemo} from '@/hooks/use-demo';
import {date} from '@/services/mock-data';
function CommentBox({issueId,onAdd}:{issueId:string;onAdd:(text:string)=>void}){const[text,setText]=useState('');return <form className="comment-form" onSubmit={e=>{e.preventDefault();if(!text.trim())return;onAdd(text);setText('')}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Adicionar comentário sobre este ponto" aria-label={`Comentar pendência ${issueId}`}/><button className="btn" type="submit"><MessageSquare size={14}/></button></form>}
export function AnalysisDetail(){const{id}=useParams<{id:string}>();const router=useRouter();const{projects,analyses,update,notice}=useDemo();const analysis=analyses.find(a=>a.id===id);if(!analysis)return <div className="panel">Análise não encontrada. <Link className="text-link" href="/arqcheck">Voltar</Link></div>;const project=projects.find(p=>p.id===analysis.projectId);function toggle(issueId:string){update(s=>({...s,analyses:s.analyses.map(a=>a.id!==id?a:{...a,issues:a.issues.map(i=>i.id===issueId?{...i,resolved:!i.resolved}:i)})}));notice('Pendência atualizada.')}function comment(issueId:string,text:string){update(s=>({...s,analyses:s.analyses.map(a=>a.id!==id?a:{...a,issues:a.issues.map(i=>i.id===issueId?{...i,comments:[...i.comments,text]}:i)})}))}async function exportPdf(){const {jsPDF}=await import('jspdf');const doc=new jsPDF();doc.setFontSize(16);doc.text('ARQ.AI · Relatório ArqCheck',14,18);doc.setFontSize(11);doc.text(`Projeto: ${project?.name||'-'}`,14,30);doc.text(`Data da análise: ${date(analysis!.date)}`,14,37);doc.text(`Score de consistência: ${analysis!.score}%`,14,44);doc.text(`Documentos analisados: ${analysis!.documents}`,14,51);let y=64;doc.setFontSize(12);doc.text('Pendências identificadas',14,y);y+=8;doc.setFontSize(10);analysis!.issues.forEach((it,i)=>{doc.text(`${i+1}. [${it.priority}] ${it.title}${it.resolved?' (resolvida)':''}`,14,y);y+=6;const lines=doc.splitTextToSize(it.detail,180);doc.text(lines,18,y);y+=lines.length*5+4});doc.save(`arqcheck-${project?.name||'relatorio'}.pdf`);notice('Relatório exportado em PDF.')}const open=analysis.issues.filter(i=>!i.resolved).length;return <><button className="btn subtle" onClick={()=>router.push('/arqcheck')} style={{marginBottom:18}}><ArrowLeft size={15}/>Voltar ao ArqCheck</button><PageHeader eyebrow="RELATÓRIO DE ANÁLISE" title={project?.name||'Projeto'} description={`Análise de ${date(analysis.date)} · ${analysis.documents} documentos · score ${analysis.score}%`}><StatusBadge value={open>0?`${open} pendências`:'Resolvido'}/><button className="btn" onClick={exportPdf}><Download size={15}/>Exportar PDF</button></PageHeader>{analysis.issues.map(issue=><div key={issue.id} className={'issue-card '+(issue.resolved?'resolved':'')}><div className="issue-head"><strong>{issue.title}</strong><StatusBadge value={issue.priority}/></div><p>{issue.detail}</p><div className="issue-actions"><button className="btn" onClick={()=>toggle(issue.id)}><Check size={14}/>{issue.resolved?'Reabrir':'Marcar como resolvida'}</button></div>{issue.comments.length>0&&<div className="issue-comments">{issue.comments.map((c,i)=><div key={i} className="comment">{c}</div>)}</div>}<CommentBox issueId={issue.id} onAdd={t=>comment(issue.id,t)}/></div>)}</>}
