'use client';
import {ArrowUpRight,ArrowDownUp,Search,Inbox} from 'lucide-react';
import {useState} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
export function Picker({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export function StatusBadge({value}:{value:string}){return <span className={'badge '+(/Alto|Alta|atras|crític/.test(value)?'red':/Médio|Média|Revisão|Atenção|Aguardando/.test(value)?'amber':/Concluído|Baixo|Processado|Resolvid/.test(value)?'green':'neutral')}><i/>{value}</span>}
export const RiskBadge=StatusBadge;
export function MetricCard({label,value,change,icon:Icon}:{label:string;value:string|number;change?:string;icon?:React.ElementType}){return <div className="metric"><div className="metric-label">{label}{Icon&&<Icon size={17}/>}</div><strong>{value}</strong><small><ArrowUpRight size={13}/>{change||'No período selecionado'}</small></div>}
export function PageHeader({title,description,children,eyebrow}:{title:string;description?:string;children?:React.ReactNode;eyebrow?:string}){return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="actions">{children}</div></div>}
export function ChartCard({title,subtitle,children,action}:{title:string;subtitle?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="panel"><div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>}
export function SearchInput({value,onChange,placeholder='Buscar...'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <label className="search"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>}
export function DataTable<T>({rows,columns,onRow}:{rows:T[];columns:{label:string;value:(row:T)=>React.ReactNode;sort?:(row:T)=>string|number}[];onRow?:(row:T)=>void}){const[sort,setSort]=useState({i:-1,dir:1});const sorted=[...rows].sort((a,b)=>{const fn=columns[sort.i]?.sort;if(!fn)return 0;const av=fn(a),bv=fn(b);return(typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'pt-BR'))*sort.dir});return rows.length?<Table><TableHeader><TableRow>{columns.map((c,i)=><TableHead key={c.label}>{c.sort?<button className="sort" onClick={()=>setSort({i,dir:sort.i===i?-sort.dir:1})}>{c.label}<ArrowDownUp size={12}/></button>:c.label}</TableHead>)}</TableRow></TableHeader><TableBody>{sorted.map((r,i)=><TableRow key={i} className={onRow?'clickable':''} onClick={()=>onRow?.(r)}>{columns.map(c=><TableCell key={c.label}>{c.value(r)}</TableCell>)}</TableRow>)}</TableBody></Table>:<Empty><EmptyHeader><Inbox/><EmptyTitle>Nenhum resultado encontrado</EmptyTitle><EmptyDescription>Ajuste os filtros para encontrar o que procura.</EmptyDescription></EmptyHeader></Empty>}
