'use client';
import {useState,Suspense} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {Plus} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {PageHeader,Picker,StatusBadge,SearchInput,DataTable} from '@/components/common';
import {useDemo} from '@/hooks/use-demo';
import {statuses,date} from '@/services/mock-data';
import type {Project} from '@/types';
const risks=['Baixo','Médio','Alto'];
const types=['Residencial','Comercial'];
function NewProjectSheet({open,onOpenChange}:{open:boolean;onOpenChange:(v:boolean)=>void}){const{projects,update,notice}=useDemo();const router=useRouter();const[form,setForm]=useState({name:'',client:'',type:types[0],owner:'Ana Martins',deadline:'2026-10-15'});function submit(e:React.SyntheticEvent<HTMLFormElement>){e.preventDefault();if(!form.name.trim()||!form.client.trim())return;const id=String(projects.length+1+Date.now()%1000);const project:Project={id,name:form.name,client:form.client,type:form.type,owner:form.owner,stage:'Estudo Preliminar',status:'Em desenvolvimento',deadline:form.deadline,progress:0,risk:'Baixo',area:0,revenue:0,cost:0,hours:0,createdAt:'2026-09-07'};update(s=>({...s,projects:[project,...s.projects]}));notice('Projeto criado com sucesso.');onOpenChange(false);router.push(`/projects/${id}`)}return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="drawer"><SheetTitle>Novo projeto</SheetTitle><SheetDescription>Cadastre um projeto para começar a usar o ARQ.AI</SheetDescription><form onSubmit={submit}><div className="form-grid" style={{gridTemplateColumns:'1fr'}}><label className="field">Nome do projeto<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex: Residencial Boa Viagem"/></label><label className="field">Cliente<input required value={form.client} onChange={e=>setForm({...form,client:e.target.value})} placeholder="Nome do cliente"/></label></div><div className="form-grid"><label className="field">Tipo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label className="field">Responsável<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label className="field">Prazo<input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label></div><div className="sheet-actions"><button type="button" className="btn" onClick={()=>onOpenChange(false)}>Cancelar</button><button type="submit" className="btn primary">Criar projeto</button></div></form></SheetContent></Sheet>}
function ProjectsView(){const{projects}=useDemo();const params=useSearchParams();const[search,setSearch]=useState('');const[status,setStatus]=useState('Todos');const[risk,setRisk]=useState('Todos');const[sheetOpen,setSheetOpen]=useState(params.get('new')==='1');const router=useRouter();const filtered=projects.filter(p=>(status==='Todos'||p.status===status)&&(risk==='Todos'||p.risk===risk)&&(p.name.toLowerCase().includes(search.toLowerCase())||p.client.toLowerCase().includes(search.toLowerCase())));return <><PageHeader eyebrow="PORTFÓLIO" title="Projetos" description={`${projects.length} projetos no seu escritório demonstrativo.`}><SearchInput value={search} onChange={setSearch} placeholder="Buscar por projeto ou cliente"/><Picker label="Status" value={status} onChange={setStatus} options={['Todos',...statuses]}/><Picker label="Risco" value={risk} onChange={setRisk} options={['Todos',...risks]}/><button className="btn primary" onClick={()=>setSheetOpen(true)}><Plus size={16}/>Novo projeto</button></PageHeader><DataTable rows={filtered} onRow={p=>router.push(`/projects/${p.id}`)} columns={[{label:'Projeto',value:p=><div><strong>{p.name}</strong><small>{p.client}</small></div>,sort:p=>p.name},{label:'Tipo',value:p=>p.type,sort:p=>p.type},{label:'Responsável',value:p=>p.owner,sort:p=>p.owner},{label:'Etapa',value:p=>p.stage},{label:'Status',value:p=><StatusBadge value={p.status}/>,sort:p=>p.status},{label:'Prazo',value:p=>date(p.deadline),sort:p=>p.deadline},{label:'Progresso',value:p=><div className="focus-progress" style={{width:80}}><span>{p.progress}%</span><progress max="100" value={p.progress}/></div>,sort:p=>p.progress},{label:'Risco',value:p=><StatusBadge value={p.risk}/>,sort:p=>p.risk}]}/><NewProjectSheet open={sheetOpen} onOpenChange={setSheetOpen}/></>}
export default function Page(){return <Suspense><ProjectsView/></Suspense>}
