// Help assistant knowledge base: how-to answers about the product, with deep links. Pure (runs under plain node).
// ponytail: keyword retrieval over ~20 articles; swap findHelp() for an LLM with these articles as context when the backend exists.

export type HelpLink = { label: string; href: string };
export type HelpArticle = { id: string; title: string; words: string[]; steps: string[]; links: HelpLink[]; area: string };

const P = '/projects/1/?tab=';
export const ARTICLES: HelpArticle[] = [
  { id: 'check-start', area: 'arqcheck', title: 'Ativar o ArqCheck contínuo', words: ['arqcheck', 'check', 'parecer', 'ativar', 'monitorar', 'monitoramento', 'analise', 'verificacao', 'continuo'], steps: ['Abra o projeto e vá na aba ArqCheck.', 'Clique em "Gerar parecer inicial e ativar".', 'A partir daí, cada documento novo, pendência alterada ou mudança de custo dispara uma nova análise sozinha.', 'Para ativar em vários projetos de uma vez, use "Ativar em todos os projetos" na página ArqCheck.'], links: [{ label: 'ArqCheck do projeto', href: `${P}check` }, { label: 'Página ArqCheck', href: '/arqcheck' }] },
  { id: 'check-demo', area: 'arqcheck', title: 'Mostrar que o ArqCheck fica rodando', words: ['simular', 'demonstrar', 'rodando', 'demo', 'evento', 'automatico', 'sozinho', 'apresentacao'], steps: ['Com o monitoramento ativo, clique em "Simular evento".', 'Escolha, por exemplo, "Chega a planta revisada com a área do memorial".', 'Em cerca de 1 segundo o ArqCheck reanalisa: o score sobe, o ponto some e o card vai para Concluído no Kanban.', 'A linha do tempo "Atividade do ArqCheck" mostra o que cada análise fez.'], links: [{ label: 'ArqCheck do projeto', href: `${P}check` }] },
  { id: 'kanban', area: 'kanban', title: 'Kanban e pendências do ArqCheck', words: ['kanban', 'card', 'cards', 'coluna', 'pendencia', 'pendencias', 'fechar', 'reabrir', 'concluido', 'mover'], steps: ['Cada ponto do ArqCheck vira pendência e card no Kanban, na coluna certa.', 'Mova o card pelo seletor de coluna. Ao ir para Concluído, a pendência fecha.', 'Se o problema continuar, a próxima análise reabre o card com um comentário.', 'Quando o problema some da base, o card fecha sozinho.'], links: [{ label: 'Kanban do projeto', href: `${P}kanban` }, { label: 'Pendências', href: `${P}pending` }] },
  { id: 'quant-start', area: 'arqquant', title: 'Gerar o levantamento no ArqQuant', words: ['arqquant', 'quant', 'levantamento', 'layout', 'planta', 'gerar', 'ambientes', 'quantitativo', 'quantitativos'], steps: ['Abra a aba ArqQuant do projeto.', 'Clique em "Gerar layout pela IA" para montar os ambientes a partir da área do memorial, ou em "Enviar modelo BIM" (.ifc, .rvt).', 'Os quantitativos (piso, alvenaria, revestimento, forro, impermeabilização) aparecem embaixo e vão direto para o ArqBudget.'], links: [{ label: 'ArqQuant do projeto', href: `${P}quant` }] },
  { id: 'bim', area: 'arqquant', title: 'Importar modelo BIM', words: ['bim', 'ifc', 'rvt', 'revit', 'importar', 'modelo', 'arquivo'], steps: ['No ArqQuant, clique em "Enviar modelo BIM" ou "Reimportar BIM".', 'Formatos aceitos: .ifc, .ifczip e .rvt.', 'A IA lê os espaços (IfcSpace) e paredes e converte em ambientes editáveis.'], links: [{ label: 'ArqQuant do projeto', href: `${P}quant` }] },
  { id: 'plan-edit', area: 'arqquant', title: 'Editar a planta', words: ['editar', 'arrastar', 'mover', 'redimensionar', 'tamanho', 'medida', 'medidas', 'atalho', 'atalhos', 'desfazer', 'ambiente', 'largura', 'profundidade'], steps: ['Arraste um ambiente para mover. Puxe a alça no canto para redimensionar (encaixe de 5 cm).', 'Ou digite largura, profundidade e pé-direito no painel à direita.', 'Atalhos: setas movem 5 cm (Shift: 50 cm), Delete exclui, Ctrl+D duplica, Ctrl+Z desfaz, Ctrl+Y refaz.', 'Use "Ajustar ao memorial" para escalar tudo até a área do memorial.'], links: [{ label: 'ArqQuant do projeto', href: `${P}quant` }] },
  { id: '3d', area: 'arqquant', title: 'Usar a visualização 3D', words: ['3d', 'modelo', 'orbitar', 'girar', 'corte', 'sol', 'solar', 'sombra', 'glb', 'sketchup', 'blender', 'camera', 'fachada'], steps: ['Arraste para orbitar, botão direito para mover e roda para zoom.', 'Clique num ambiente para selecioná-lo (a planta acompanha).', 'Use "Corte" para rebaixar as paredes e ver por dentro, e "Sol" para o estudo de insolação por horário.', 'Exporte em PNG para apresentar ou em GLB para abrir no Blender, SketchUp ou Revit.'], links: [{ label: 'ArqQuant do projeto', href: `${P}quant` }] },
  { id: 'budget', area: 'arqbudget', title: 'Orçar com cotações de fornecedores', words: ['orcamento', 'orcar', 'arqbudget', 'budget', 'cotacao', 'cotacoes', 'fornecedor', 'fornecedores', 'preco', 'precos', 'sinapi', 'cub'], steps: ['Na aba ArqBudget, clique em "Gerar cenário base" (ou econômico / alto padrão).', 'Clique na fonte do preço de qualquer linha para ver SINAPI, histórico e 3 fornecedores com prazo e desvio da mediana.', 'Clique em "Usar" para trocar a fonte. Preços manuais fora da faixa de mercado ficam sinalizados.', 'Se houver levantamento no ArqQuant, as quantidades vêm da geometria.'], links: [{ label: 'ArqBudget do projeto', href: `${P}budget` }, { label: 'Página ArqBudget', href: '/arqbudget' }] },
  { id: 'budget-versions', area: 'arqbudget', title: 'Versões, cenários e envio do orçamento', words: ['versao', 'versoes', 'comparar', 'cenario', 'cenarios', 'exportar', 'excel', 'pdf', 'cliente', 'enviar'], steps: ['Troque de cenário nos três cartões do topo. O material muda, não só o preço.', '"Salvar versão" congela o orçamento. Em "Versões", compare o rascunho com qualquer versão por categoria.', 'Exporte em Excel ou PDF, ou use "Enviar ao cliente" para gerar o e-mail com o timbrado.'], links: [{ label: 'ArqBudget do projeto', href: `${P}budget` }] },
  { id: 'agents-chat', area: 'agents', title: 'Conversar com um agente', words: ['agente', 'agentes', 'chat', 'conversar', 'perguntar', 'mencionar', 'arroba', 'contexto', 'fonte', 'fontes', 'anexar', 'anexo', 'anexa'], steps: ['Abra a aba Agents do projeto ou a página ArqDocs.', 'Escolha o agente no seletor do topo.', 'Digite @ para anexar documentos, disciplinas ou bases externas à conversa.', 'Escolha o formato da entrega (Chat, PDF, Word, Planilha, E-mail) e o template antes de enviar.'], links: [{ label: 'Agents do projeto', href: `${P}agents` }, { label: 'ArqDocs', href: '/arqdocs' }] },
  { id: 'agents-create', area: 'agents', title: 'Criar um agente', words: ['criar', 'novo', 'agente', 'prompt', 'obrigatorio', 'obrigatorios', 'formato', 'formatos', 'missao'], steps: ['No seletor de agentes, clique em "+ Criar agente" (ou em "Criar agente" na página ArqDocs).', 'Defina missão, regras, arquivos obrigatórios, formatos de entrega, template padrão e perguntas sugeridas.', 'O prompt é montado ao vivo ao lado. O agente nasce como rascunho e já aparece no seletor.'], links: [{ label: 'ArqDocs', href: '/arqdocs' }] },
  { id: 'rbac', area: 'agents', title: 'Perfis, permissões e contexto global', words: ['permissao', 'permissoes', 'perfil', 'admin', 'gestor', 'membro', 'global', 'promover', 'privado', 'acesso', 'rbac'], steps: ['Membros conversam; gestores podem "Tornar Contexto Global" uma resposta; admins mudam o acesso dos documentos e veem a auditoria.', 'Na demo, troque o perfil no seletor com escudo ao lado do agente.', 'Documentos podem ser Privado, Equipa ou IA global na aba Docs.'], links: [{ label: 'Docs do projeto', href: `${P}docs` }] },
  { id: 'docs', area: 'docs', title: 'Enviar documentos e conectar bases', words: ['documento', 'documentos', 'enviar', 'upload', 'base', 'externa', 'sql', 'sharepoint', 'conectar', 'arquivos', 'docs', 'interagir'], steps: ['Na aba Docs, use "Enviar arquivos" ou "Conectar base" (SQL, SharePoint, API, Drive).', 'Filtre por Arquivos, Bases conectadas ou Contexto validado.', '"Interagir" abre o chat do agente já com aquele documento anexado.'], links: [{ label: 'Docs do projeto', href: `${P}docs` }] },
  { id: 'radar-prompt', area: 'arqradar', title: 'Criar uma visualização no ArqRadar', words: ['radar', 'arqradar', 'grafico', 'graficos', 'visualizacao', 'dashboard', 'indicador', 'indicadores', 'prompt', 'aba'], steps: ['Abra o ArqRadar e clique em "+ Nova visualização".', 'Descreva em português, por exemplo "margem por projeto" ou "pendências abertas por responsável".', 'Ajuste fonte, medida, agrupamento e tipo de gráfico nos seletores e clique em "Salvar como aba".'], links: [{ label: 'ArqRadar', href: '/arqradar' }, { label: 'Radar do projeto', href: `${P}radar` }] },
  { id: 'radar-canvas', area: 'arqradar', title: 'Dashboard conectado com PROCX e correlações', words: ['conectado', 'canvas', 'ligacao', 'ligacoes', 'procv', 'procx', 'join', 'correlacao', 'cruzar', 'planilha', 'erp'], steps: ['No ArqRadar, abra "Dashboard conectado".', 'Clique em "IA: sugerir ligações" ou ligue manualmente: clique num campo e depois no campo correspondente de outra fonte.', 'Clique no rótulo da ligação para alternar entre PROCX e CONT.SE.', '"Gerar dashboard" mostra números, análise da IA, gráficos e a tabela cruzada, com filtros de período, cliente e risco.'], links: [{ label: 'ArqRadar', href: '/arqradar' }] },
  { id: 'radar-send', area: 'arqradar', title: 'Enviar ou agendar um dashboard por e-mail', words: ['email', 'e-mail', 'agendar', 'agendamento', 'semanal', 'diario', 'mensal', 'png', 'imagem', 'envio'], steps: ['No dashboard conectado, clique em "Enviar ou agendar".', 'Escolha o título, o destinatário e quando: agora, diário, semanal ou mensal.', 'O dashboard vai como imagem no corpo do e-mail, com a análise da IA. "Exportar PNG" baixa só a imagem.'], links: [{ label: 'ArqRadar', href: '/arqradar' }] },
  { id: 'history', area: 'history', title: 'Histórico e auditoria', words: ['historico', 'auditoria', 'conversas', 'rastreabilidade', 'log', 'quem'], steps: ['Na aba Histórico do projeto, "Minhas conversas" reabre qualquer conversa com agentes no ponto exato.', 'Admins veem a "Auditoria de interações" com filtros por utilizador, agente e fonte.'], links: [{ label: 'Histórico do projeto', href: `${P}history` }] },
  { id: 'templates', area: 'templates', title: 'Templates e timbrados', words: ['template', 'templates', 'timbrado', 'logo', 'marca', 'modelo'], steps: ['Na aba Templates do projeto, defina o template padrão e os dados de marca.', 'Os agentes, o parecer do ArqCheck e o orçamento usam esse template ao gerar PDF, Word e e-mail.'], links: [{ label: 'Templates do projeto', href: `${P}templates` }] },
  { id: 'home', area: 'dashboard', title: 'Caixa de decisões do Dashboard', words: ['inicio', 'inicial', 'dashboard', 'caixa', 'decisoes', 'hoje', 'passos', 'economia'], steps: ['"Precisa de você hoje" reúne o que é urgente de todos os módulos. Cada ação abre a aba certa do projeto.', 'Marque com ✓ o que já resolveu para zerar a caixa.', '"Primeiros passos" guia a configuração; "Economia encontrada pela IA" soma o que as cotações economizaram.'], links: [{ label: 'Dashboard', href: '/dashboard' }] },
  { id: 'theme', area: 'geral', title: 'Modo escuro', words: ['escuro', 'claro', 'tema', 'dark', 'noite', 'cor', 'cores'], steps: ['Use o botão de lua/sol no topo da tela. O ícone da aba acompanha o tema.'], links: [] },
  { id: 'demo-data', area: 'geral', title: 'Dados da demonstração', words: ['dados', 'demo', 'demonstracao', 'apagar', 'resetar', 'limpar', 'salvo', 'salvar', 'perdi'], steps: ['Esta é uma demonstração com dados fictícios, guardados na aba do navegador.', 'Fechar a aba volta tudo ao estado inicial.'], links: [] },
];

export const norm = (t: string) => t.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();

export function findHelp(question: string, area?: string) {
  const tokens = norm(question).split(/[^a-z0-9@.-]+/).filter((w) => w.length > 1);
  const scored = ARTICLES.map((a) => {
    let score = 0;
    for (const t of tokens) for (const w of a.words) if (t === w || (w.length > 4 && t.startsWith(w.slice(0, -1)))) score += w.length > 6 ? 1.3 : 1;
    if (norm(question).includes(norm(a.title))) score += 3;
    if (area && a.area === area) score += 0.4; // tie-break toward the page the user is on
    return { a, score };
  }).sort((x, y) => y.score - x.score);
  return { best: scored[0].score >= 1 ? scored[0].a : null, related: scored.slice(1, 4).filter((s) => s.score >= 1).map((s) => s.a) };
}

// Data questions go to the portfolio answerer instead of the how-to base.
export const isDataQuestion = (q: string) => /\b(risco|rrt|horas?|diverg|rentab|rentav|margem|compare|comparar|quais projetos|quanto)\b/.test(norm(q)) && !/\bcomo\b/.test(norm(q));

export function areaFor(pathname: string, search = '') {
  const tab = new URLSearchParams(search).get('tab');
  if (tab) return ({ check: 'arqcheck', quant: 'arqquant', budget: 'arqbudget', radar: 'arqradar', agents: 'agents', docs: 'docs', kanban: 'kanban', pending: 'kanban', history: 'history', templates: 'templates' } as Record<string, string>)[tab];
  const seg = pathname.split('/')[1];
  return ({ arqcheck: 'arqcheck', arqquant: 'arqquant', arqbudget: 'arqbudget', arqradar: 'arqradar', arqdocs: 'agents', dashboard: 'dashboard' } as Record<string, string>)[seg];
}
